DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS items; --возможно, потребуется каскаде

DROP TABLE IF EXISTS bookings;

CREATE TABLE IF NOT EXISTS users (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, --нужна ли обоюдная ссылка
                                    name varchar(255) NOT NULL,
                                    CONSTRAINT email varchar(512) UNIQUE NOT NULL
                                 );

CREATE TABLE IF NOT EXISTS items (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    name varchar(200) NOT NULL,
                                    description varchar(400) NOT NULL,
                                    items_available boolean DEFAULT TRUE,
                                    owners_ids BIGINT REFERENCES users(id) ON DELETE RESTRICT,
                                    requests_ids BIGINT --дописать ссылку, зависит от item request
                                 );

CREATE TABLE IF NOT EXISTS bookings (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      start_time timestamp,
                                      end_time timestamp,
                                      items_ids BIGINT REFERENCES items(id) ON DELETE RESTRICT,
                                      bookers_ids BIGINT REFERENCES users(id) ON DELETE RESTRICT,
                                      status ENUM('WAITING', 'APPROVED', 'REJECTED', 'CANCELED') NOT NULL
                                      );